cmd_/home/factory_testbed/project/NCB-1515/property/GobiSerial/S2.30N2.48/GobiNet/usbnet_4_4_xx.o := gcc -Wp,-MD,/home/factory_testbed/project/NCB-1515/property/GobiSerial/S2.30N2.48/GobiNet/.usbnet_4_4_xx.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I./arch/x86/include -I./arch/x86/include/generated/uapi -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -Os --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO  -DMODULE  -DKBUILD_BASENAME='"usbnet_4_4_xx"'  -DKBUILD_MODNAME='"GobiNet"' -c -o /home/factory_testbed/project/NCB-1515/property/GobiSerial/S2.30N2.48/GobiNet/usbnet_4_4_xx.o /home/factory_testbed/project/NCB-1515/property/GobiSerial/S2.30N2.48/GobiNet/usbnet_4_4_xx.c

source_/home/factory_testbed/project/NCB-1515/property/GobiSerial/S2.30N2.48/GobiNet/usbnet_4_4_xx.o := /home/factory_testbed/project/NCB-1515/property/GobiSerial/S2.30N2.48/GobiNet/usbnet_4_4_xx.c

deps_/home/factory_testbed/project/NCB-1515/property/GobiSerial/S2.30N2.48/GobiNet/usbnet_4_4_xx.o := \
    $(wildcard include/config/pm.h) \
  include/generated/uapi/linux/version.h \

/home/factory_testbed/project/NCB-1515/property/GobiSerial/S2.30N2.48/GobiNet/usbnet_4_4_xx.o: $(deps_/home/factory_testbed/project/NCB-1515/property/GobiSerial/S2.30N2.48/GobiNet/usbnet_4_4_xx.o)

$(deps_/home/factory_testbed/project/NCB-1515/property/GobiSerial/S2.30N2.48/GobiNet/usbnet_4_4_xx.o):
